### ISSUE TITLE
Example for mcuboot_CONFIG_BOOT_SIGNATURE_KEY_FILE does not work in ncs 2.2.0

### ISSUE THREAD

**Issue by gte1** [hellesvik-nordic/samples_for_nrf_connect_sdk#2]
https://github.com/hellesvik-nordic/samples_for_nrf_connect_sdk/blob/56e9490fcab9a5b6cdd6f289cdf0a5ea43cb97ba/bootloader_samples/keys_and_signatures/mcuboot_smp_custom_key/CMakeLists.txt#L5

I get warning: 
C:/ncs_proj/samples_for_nrf_connect_sdk-main/bootloader_samples/keys_and_signatures/mcuboot_smp_custom_key/build/mcuboot/zephyr/misc/generated/extra_kconfig_options.conf:2: warning: malformed string literal in assignment to BOOT_SIGNATURE_KEY_FILE (defined at C:/ncs/v2.2.0/nrf/modules/mcuboot/boot/zephyr/Kconfig:58, C:/ncs/v2.2.0/bootloader/mcuboot/boot/zephyr/Kconfig:131, C:/ncs/v2.2.0/nrf/modules/mcuboot/Kconfig:3). Assignment ignored.

error: Aborting due to Kconfig warnings

**Comment by gte1** [comment]
This seems to work in ncs 2.2.0
`set(mcuboot_CONFIG_BOOT_SIGNATURE_KEY_FILE \"${CMAKE_CURRENT_SOURCE_DIR}/custom_key_dir/custom_priv.pem\")
`

**Comment by hellesvik-nordic** [comment]
Thanks for the fix!
Fixed in c9d8898024e1a1ab7abaddf89b69b8323aeef912
