### ISSUE TITLE
mcuboot_smp_ble_simultaneous west build failed

### ISSUE THREAD

**Issue by snowuyl** [hellesvik-nordic/samples_for_nrf_connect_sdk#6]
I would like to build https://github.com/hellesvik-nordic/samples_for_nrf_connect_sdk/tree/main/bootloader_samples/nrf5340/mcuboot_smp_ble_simultaneous. But it failed to build with the following messages.

D:\ncs\v2.4.0\bootloader\mcuboot\samples\zephyr\mcuboot_smp_ble_simultaneous>west build -b nrf5340dk_nrf5340_cpuapp
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: D:/ncs/v2.4.0/bootloader/mcuboot/samples/zephyr/mcuboot_smp_ble_simultaneous
-- CMake version: 3.20.5
-- Using NCS Toolchain 2.4.0 for building. (D:/ncs/toolchains/31f4403e35/cmake)
-- Found Python3: D:/ncs/toolchains/31f4403e35/opt/bin/python.exe (found suitable exact version "3.8.2") found components: Interpreter
-- Cache files will be written to: D:/ncs/v2.4.0/zephyr/.cache
-- Zephyr version: 3.3.99 (D:/ncs/v2.4.0/zephyr)
-- Found west (found suitable version "1.0.0", minimum required is "0.7.1")
-- Board: nrf5340dk_nrf5340_cpuapp
-- Found host-tools: zephyr 0.16.0 (D:/ncs/toolchains/31f4403e35/opt/zephyr-sdk)
-- Found toolchain: zephyr 0.16.0 (D:/ncs/toolchains/31f4403e35/opt/zephyr-sdk)
-- Found Dtc: D:/ncs/toolchains/31f4403e35/opt/bin/dtc.exe (found suitable version "1.4.7", minimum required is "1.4.6")
-- Found BOARD.dts: D:/ncs/v2.4.0/zephyr/boards/arm/nrf5340dk_nrf5340/nrf5340dk_nrf5340_cpuapp.dts
-- Found devicetree overlay: D:/ncs/v2.4.0/bootloader/mcuboot/samples/zephyr/mcuboot_smp_ble_simultaneous/app.overlay
-- Generated zephyr.dts: D:/ncs/v2.4.0/bootloader/mcuboot/samples/zephyr/mcuboot_smp_ble_simultaneous/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: D:/ncs/v2.4.0/bootloader/mcuboot/samples/zephyr/mcuboot_smp_ble_simultaneous/build/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: D:/ncs/v2.4.0/bootloader/mcuboot/samples/zephyr/mcuboot_smp_ble_simultaneous/build/zephyr/dts.cmake

D:/ncs/v2.4.0/bootloader/mcuboot/samples/zephyr/mcuboot_smp_ble_simultaneous/prj.conf:6: warning: attempt to assign the value 'y' to the undefined symbol MCUMGR_SMP_UART

D:/ncs/v2.4.0/bootloader/mcuboot/samples/zephyr/mcuboot_smp_ble_simultaneous/prj.conf:7: warning: attempt to assign the value 'y' to the undefined symbol MCUMGR_CMD_IMG_MGMT
Parsing D:/ncs/v2.4.0/zephyr/Kconfig
Loaded configuration 'D:/ncs/v2.4.0/zephyr/boards/arm/nrf5340dk_nrf5340/nrf5340dk_nrf5340_cpuapp_defconfig'
Merged configuration 'D:/ncs/v2.4.0/bootloader/mcuboot/samples/zephyr/mcuboot_smp_ble_simultaneous/prj.conf'

error: Aborting due to Kconfig warnings

CMake Error at D:/ncs/v2.4.0/zephyr/cmake/modules/kconfig.cmake:339 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  D:/ncs/v2.4.0/nrf/cmake/modules/kconfig.cmake:29 (include)
  D:/ncs/v2.4.0/zephyr/cmake/modules/zephyr_default.cmake:115 (include)
  D:/ncs/v2.4.0/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  D:/ncs/v2.4.0/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: 'D:\ncs\toolchains\31f4403e35\opt\bin\cmake.EXE' '-DWEST_PYTHON=D:\ncs\toolchains\31f    f4403e35\opt\bin\python.exe' '-BD:\ncs\v2.4.0\bootloader\mcuboot\samples\zephyr\mcuboot_smp_ble_simultaneous\build' -GNinja -DBOARD=nrf5340dk_nrf5340_cpuapp '-SD:\ncs\v2.4.0\bootloader\mcuboot\samples\zephyr\mcuboot_smp_ble_simultaneous'

Procedures to reproduce this issue are as follows.

1. Unzipping [mcuboot_smp_ble_simultaneous.zip](https://devzone.nordicsemi.com/cfs-file/__key/communityserver-discussions-components-files/4/5857.mcuboot_5F00_smp_5F00_ble_5F00_simultaneous.zip) to D:\ncs\v2.4.0\bootloader\mcuboot\samples\zephyr\ folder.

2. cd D:\ncs\v2.4.0\bootloader\mcuboot\samples\zephyr\mcuboot_smp_ble_simultaneous

3. west build -b nrf5340dk_nrf5340_cpuapp

**Comment by snowuyl** [comment]
[mcuboot_smp_ble_simultaneous.zip](https://github.com/hellesvik-nordic/samples_for_nrf_connect_sdk/files/12213257/mcuboot_smp_ble_simultaneous.zip)

**Comment by hellesvik-nordic** [comment]
Hi
Is this still an issue?
Do you have an [DevZone](https://github.com/hellesvik-nordic/samples_for_nrf_connect_sdk/issues/devzone.nordicsemi.com/) ticket for this problem?

**Comment by hellesvik-nordic** [comment]
Closed due to inactivity
