### ISSUE TITLE
mcuboot_smp_ble_simultaneous error: This image has already been flashed (has value of the previous image matches current one)

### ISSUE THREAD

**Issue by snowuyl** [hellesvik-nordic/samples_for_nrf_connect_sdk#7]
I follow procedures list on https://github.com/hellesvik-nordic/samples_for_nrf_connect_sdk/tree/main/bootloader_samples/nrf5340/mcuboot_smp_ble_simultaneous. But I encounter "Error: This image has already been flashed (has value of the previous image matches current one)".

**Comment by snowuyl** [comment]
![DFU_failed](https://github.com/hellesvik-nordic/samples_for_nrf_connect_sdk/assets/8336439/38ca40ad-182d-4f55-8e27-4ef6545acfb5)

**Comment by hellesvik-nordic** [comment]
Hi
Is this still an issue?
Do you have an [DevZone](https://github.com/hellesvik-nordic/samples_for_nrf_connect_sdk/issues/devzone.nordicsemi.com/) ticket for this problem?

**Comment by hellesvik-nordic** [comment]
Closed due to inactivity
